# Generated by Django 4.0.3 on 2022-04-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
